import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PinnacleAI - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={`${inter.className}`} suppressHydrationWarning>
          <NextThemesProvider
            defaultTheme="dark"
            attribute="class"
            enableSystem
            disableTransitionOnChange
          >
            {/* Header */}
            <Header />

            {/* Main Content */}
            <main className="min-h-screen">{children}</main>
               <Toaster richColors/>
            {/* Footer */}
            <footer className="bg-muted/50 text-gray-400 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made by Piyush</p>
              </div>
            </footer>
          </NextThemesProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
// import { Toaster } from "sonner";
// import Header from "@/components/Header";
// import { ThemeProvider } from "@/components/theme-provider";
// import { dark } from "@clerk/themes";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "AI Career Coach",
//   description: "",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider
//       appearance={{
//         baseTheme: dark,
//       }}
//     >
//       <html lang="en" suppressHydrationWarning>
//         <head>
//           <link rel="icon" href="/logo.png" sizes="any" />
//         </head>
//         <body className={`${inter.className}`}>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="dark"
//             enableSystem
//             disableTransitionOnChange
//           >
//             <Header />
//             <main className="flex-1 overflow-auto">{children}</main>

//             <Toaster richColors />

//             <footer className="bg-muted/50 py-12">
//               <div className="container mx-auto px-4 text-center text-gray-200">
//                 <p>Made by Piyush</p>
//               </div>
//             </footer>
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
